### ISSUE TITLE
Incorrect method in patch files

### ISSUE THREAD

**Issue by dwoz** [rossengeorgiev/salt-security-backports#1]
https://github.com/rossengeorgiev/salt-security-backports/blob/3687cd5533b14ba143d3792be562957c6250eafc/2016.11.10_CVE-2020-11651.patch#L78

`_file_find_and_hash` should be `_file_stat_and_hash`

https://github.com/saltstack/salt/issues/57027

**Comment by rossengeorgiev** [comment]
Hi @dwoz, you mean `_file_hash_and_stat`, right?

Also, for `2016`, that one doesn't seem available:

https://github.com/saltstack/salt/blob/302776b03c38514667e2292ef3553b6442ee776d/salt/master.py#L975-L990
