### ISSUE TITLE
Check supporting minion?

### ISSUE THREAD

**Issue by roflmao** [rossengeorgiev/salt-security-backports#15]
Would it be a good measurement to support checking the salt-minon as well? As i can read from the CVE the minions are also vulnerable.

```
$ python salt-cve-check.py --help
Traceback (most recent call last):
  File "salt-cve-check.py", line 30, in <module>
    with fopen('/var/cache/salt/master/.root_key') as keyfd:
IOError: [Errno 2] No such file or directory: '/var/cache/salt/master/.root_key'
```

**Comment by rossengeorgiev** [comment]
salt-minion alone are not affected. The vulnerabilities allows remote attacker to execute commands on minions via a vulnerable salt-master.
